spring:
  application:
    name: s31641-TPO
  banner:
    location: logo-app
    charset: UTF-8
  profiles:
    active: lowercase
  h2:
    console:
      enabled: true
      path: /my-h2-console
  datasource:
    url: jdbc:h2:file:./db/dictionary;DATABASE_TO_UPPER=false
    username: narbo
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

pl.edu.pja.tpo02.words.csv: src\main\resources\words.csv