INSERT INTO Entry (english, german, polish) VALUES
                                                ('Hello', 'Hallo', 'Cześć'),
                                                ('Goodbye', 'Auf Wiedersehen', 'Do widzenia'),
                                                ('Please', 'Bitte', 'Proszę'),
                                                ('Thank you', 'Danke', 'Dziękuję'),
                                                ('Yes', 'Ja', 'Tak'),
                                                ('No', 'Nein', 'Nie'),
                                                ('Love', 'Liebe', 'Miłość'),
                                                ('Friend', 'Freund', 'Przyjaciel'),
                                                ('Family', 'Familie', 'Rodzina'),
                                                ('House', 'Haus', 'Dom'),
                                                ('Water', 'Wasser', 'Woda'),
                                                ('Food', 'Essen', 'Jedzenie'),
                                                ('Book', 'Buch', 'Książka'),
                                                ('Car', 'Auto', 'Samochód'),
                                                ('School', 'Schule', 'Szkoła'),
                                                ('Work', 'Arbeit', 'Praca'),
                                                ('Morning', 'Morgen', 'Rano'),
                                                ('Night', 'Nacht', 'Noc'),
                                                ('Day', 'Tag', 'Dzień'),
                                                ('Sun', 'Sonne', 'Słońce'),
                                                ('Moon', 'Mond', 'Księżyc'),
                                                ('Happy', 'Glücklich', 'Szczęśliwy'),
                                                ('Sad', 'Traurig', 'Smutny'),
                                                ('Beautiful', 'Schön', 'Piękny'),
                                                ('Strong', 'Stark', 'Silny'),
                                                ('Good', 'Gut', 'Dobry'),
                                                ('Bad', 'Schlecht', 'Zły'),
                                                ('Small', 'Klein', 'Mały'),
                                                ('Big', 'Groß', 'Duży'),
                                                ('Old', 'Alt', 'Stary'),
                                                ('Young', 'Jung', 'Młody'),
                                                ('Cold', 'Kalt', 'Zimny'),
                                                ('Hot', 'Heiß', 'Gorący');